# SwiftLint Configuration for Weather App
# https://github.com/realm/SwiftLint

# Paths to ignore
excluded:
  - DerivedData
  - .build
  - Pods
  - Carthage
  - weatherTests
  - weatherUITests

# Rules configuration
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - implicitly_unwrapped_optional
  - missing_docs
  - private_outlet
  - private_action
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule customization
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - a
    - b
    - d

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - weatherApp
    - Andernet_Weather_Widget
    - Andernet_Weather_WidgetBundle
    - Andernet_Weather_WidgetControl
    - Andernet_Weather_WidgetLiveActivity

force_try:
  severity: warning

force_unwrapping:
  severity: warning

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

cyclomatic_complexity:
  warning: 15
  error: 25

function_parameter_count:
  warning: 6
  error: 8

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"
