#!/bin/bash
# Git Info Injection Script
# Injects git commit hash and branch into Info.plist for debugging
#
# To add as Build Phase:
# 1. Select project → target "weather" → Build Phases
# 2. + → New Run Script Phase
# 3. Name it "Inject Git Info"
# 4. Paste: "${SRCROOT}/scripts/build-phases/git-info.sh"

set -e

# Only run for Debug builds (useful for debugging)
if [ "${CONFIGURATION}" = "Release" ]; then
    echo "Skipping git info injection in Release"
    exit 0
fi

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_DIRTY=$(git diff --quiet HEAD 2>/dev/null || echo "-dirty")
BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")

# Create a BuildInfo.swift file with git metadata
BUILD_INFO_FILE="${SRCROOT}/weather/Sources/App/BuildInfo.swift"

cat > "$BUILD_INFO_FILE" << EOF
// Auto-generated by build script - DO NOT EDIT
// Generated: $BUILD_DATE

import Foundation

enum BuildInfo {
    static let gitCommit = "$GIT_HASH$GIT_DIRTY"
    static let gitBranch = "$GIT_BRANCH"
    static let buildDate = "$BUILD_DATE"
    static let configuration = "${CONFIGURATION}"
    
    static var description: String {
        "\(gitBranch)@\(gitCommit) (\(configuration))"
    }
}
EOF

echo "Git info injected: $GIT_BRANCH@$GIT_HASH$GIT_DIRTY"
